# Generated by Django 5.0.1 on 2025-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.IntegerField(default=100),
        ),
    ]
