# Generated by Django 5.0.1 on 2025-10-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
    ]
